apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ccuijen
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ccuijen
    spec:
      containers:
      - name: ccuijen
        image: docker.io/dkori/three:ccui
        ports:
        - containerPort: 80
